name: Build & Test

on:
  push:
    branches: [main]
  workflow_dispatch:

# permissions:
#   contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build with ncc
        run: |
          npm install
          npm run build

      - name: Invoke echo 1 workflow using this action
        uses: ./
        with:
          workflow: Message Echo 1
          inputs: '{"message": "blah blah"}'

      - name: Invoke echo 2 workflow using this action
        uses: ./
        with:
          workflow: echo-2.yaml

