name: Message Echo 3

on:
  workflow_dispatch:
    inputs:
      message:
        required: false
        default: 'this is echo 3'
        description: 'Message to echo'
permissions:
  contents: read

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Intentional failure
        run: exit 1
